name: article gen

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: peaceiris/actions-hugo@v2	# hugo官方提供的action，用于在任务环境中获取hugo

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        hugo-version: 'latest'

    - name: Build
      run: |
            cd scripts && go run gen.go
            mv *.md ../content/post/
            cd .. && hugo -D
            git config --global user.name 'wfsui'
            git config --global user.email 'wfsui@protonmail.com'
            git commit -am "Automated report"
            git push
